#!/usr/bin/env bash
set -x
set -e

if [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	sudo wget -O blacklist.tar.gz ${UPDATE_BLACKLIST_URL} \
 		&& tar -xzf blacklist.tar.gz -C /var/lib/squidguard/db \
 		&& rm blacklist.tar.gz \
 		&& chown proxy:proxy /var/lib/squidguard/db -R
fi


if [ ! -f /etc/squidguard/squidGuard.conf ]; then
	# if this file doesn't exist -> it is the first time
	if [  "${SQUID_UID}" != "" ]; then
		# workaround for mac os mapping problem:
		sudo usermod -u ${SQUID_UID} proxy
	fi
	# chown is required especially because directories can be mapped
	chown -R proxy:proxy /var/lib/squidguard/db /sample-config-simple /sample-config-blacklist /custom-config /var/log/squid
	chmod -R 755 /var/lib/squidguard/db

	if [  -n "${SQUID_CONFIG_SOURCE}" ]; then
	  if [ -f "${SQUID_CONFIG_SOURCE}/squidGuard.conf" ]; then
      [ -f " /etc/squidguard/squidGuard.conf" ] && rm -f  /etc/squidguard/squidGuard.conf
  		ln -s ${SQUID_CONFIG_SOURCE}/squidGuard.conf /etc/squidguard/squidGuard.conf
  	else
    	echo "no configuration found"
	  fi
	elif [  -n "${UPDATE_BLACKLIST_URL}" ]; then
	    echo "no configuration found -> use /sample-config-blacklist"
		ln -s /sample-config-blacklist/squidGuard.conf /etc/squidguard/squidGuard.conf
	else
	    echo "no configuration found -> use /sample-config-simple"
		ln -s /sample-config-simple/squidGuard.conf /etc/squidguard/squidGuard.conf
	fi
fi


# run original squid start script
exec /sbin/entrypoint.sh